import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const userName = 'Nombre del Usuario'; 
  const imageUrl = '/profile-image.jpg'; 
  const userDescription = 'Descripción breve del usuario';
  const userInterests = ['Interés 1', 'Interés 2', 'Interés 3'];

  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        <Header userName={userName} imageUrl={imageUrl} />
        <main>
          {children} 
        </main>
      </body>
    </html>
  );
};